
## Setup

WARNING: You need to set an environment variable with your Google Maps API key as follows for the application to start and for integration tests to pass

----
#Windows, dos prompt
set GOOGLE_MAPS_API_KEY=AIza....

#*nix
export GOOGLE_MAPS_API_KEY=AIza...
----

WARNING: `JAVA_HOME` must also be set to a Java8 JDK!

----
#Windows, dos prompt
set JAVA_HOME=c:....

#*nix
export JAVA_HOME=/..
----

## How To Build

The application uses Gradle so building it is as straightforward as...

----
# Clone the repo
git clone https://github.com/micke-a/shopping-service.git

#Build artifact
gradlew assemble
----

## How To Test

Start the application in order for integration tests to work

----
gradlew bootRun
----

Once the application is up and running, you can execute all tests as follows
----
gradlew check
----

To only run unit tests there is no need to start the application and you can simply run

----
gradlew test
----


## How To Run


### Start The Application

----
gradlew bootRun
----

This will startup the application using the `local` Spring profile which will load up some noddy test data,
briefly described in the <<Local Environment Test Data>> section.

### Testing Driving The Application

Once the application is up and running you can access the usual http://localhost:8080/docs/[Spring Boot Actuator Generated Documentation]

Also added springfox swagger2 library which gives the wee bit more interesting http://localhost:8080/swagger-ui.html[Swagger API Documentation] to click around

#### Local Environment Test Data

When the `local` Spring profile is active the following simple Shop test data is generated with the following long/lat
coordinates for some simple testing.

----
9........x
8.......x.
7......x..
6.....x...
5....x....
4...x.....
3..x......
2.x.......
1x........
 123456789
----

#### List All Shops

[source,json]
----
GET /shops
----

#### Find Nearest Shop

[source,json]
----
GET /shops/1.5/1.5/
----

*Note*: trailing slash is needed, otherwise the URL is truncated after the last dot


#### Add a Shop

[source,json]
----
POST /shops

{
"name": "New Shop",
"address": {
  "number": "70 Buckwells Field",
  "postCode": "SG143FF"
}
}

----

## Troubleshooting

### Getting cannot find symbol method getXyz()

If you get this in your IDE it is probably because annotation pre-processing isn't configured.

See https://www.jetbrains.com/help/idea/2016.2/configuring-annotation-processing.html for how to set this up in intellij

### Tests Are Failing, why?

Double check that you've set the `GOOGLE_MAPS_API_KEY` if not the context load test will fail.

When running integration tests you'll also need a the application running on localhost!
